name: Test Build

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and export
      uses: docker/build-push-action@v6
      with:
        context: .
        push: false
        tags: sharelatex-full:test
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=/tmp/sharelatex-full.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sharelatex-full
        path: /tmp/sharelatex-full.tar
        retention-days: 1
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Download artifact
        uses: actions/download-artifact@v5
        with:
          name: sharelatex-full
          path: /tmp
      - name: Load image
        run: docker load --input /tmp/sharelatex-full.tar
      - name: Build MWEs
        run: docker run --rm --volume $(pwd)/tests:/tests --entrypoint=/bin/bash sharelatex-full:test -c "/bin/bash /tests/compile.sh"
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./mwe/*/*.pdf
          retention-days: 7